### ISSUE TITLE
You have some problem with django 1.10

### ISSUE THREAD

**Issue by dmitryTsatsarin** [jsmits/django-logutils#10]
You have some problem with django 1.10
`TypeError: 'LoggingMiddleware' object is not callable
  File "django/core/handlers/exception.py",`

In django 1.10 your middleware class should be child of "MiddlewareMixin"

**Comment by jsmits** [comment]
Thanks, going to look into that.

Ref.: https://docs.djangoproject.com/en/1.11/topics/http/middleware/

**Comment by turacosianritesh** [comment]
Somewhere I keep getting this error from the package -

TypeError: %d format: a number is required, not unicode
Logged from file middleware.py, line 125
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not unicode

**Comment by turacosianritesh** [comment]
Your create_logger seems to have an issue -

Making below change fixes the issue i.e replace %d with %s -
log_msg = (
        "%(remote_address)s %(user_email)s %(method)s %(url)s %(status)s "
        "%(content_length)s (%(request_time).2f seconds)"
    ) 

Do you want me to raise  a PR to fix this dude?

**Comment by turacosianritesh** [comment]
content_length and status attributes

**Comment by jsmits** [comment]
Yes, a PR would be nice. Thanks for reporting this.
